### PR TITLE
custom place-holder added to the select box

### PR DESCRIPTION
**Pull request by rosepriya-jk**

### CODE REVIEW

**Comment by ionelmc** [comment]
Wouldn't "placeholder" be a better name? It's the same attribute as for the regular `<input>`.

**Comment by tinkerD** [comment]
Yeah sure. Polymer input usually take the 'label' attribute to be its default placeholder.

**Comment by ionelmc** [comment]
Here https://www.polymer-project.org/0.5/docs/elements/core-input.html I
see it mentions "placeholder attribute". Where do you see the label
attribute?


Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by tinkerD** [comment]
I was referring to the paper input element  -> 
https://www.polymer-project.org/0.5/docs/elements/paper-input.html

~Rose

**Comment by ionelmc** [comment]
Ah right. For me "placeholder" seems consistent as it's the convention in
html(5?) elements.


Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by ionelmc** [comment]
Thanks. Released as 2.3.0.

**Comment by rosepriya-jk** [comment]
Thanks
~Rose

**Pull request merged**
